export TNS_ADMIN=/home/oracle/tns_network
export ORACLE_SID=UNIBOP1


#con, prd, 
ambiente=prd

# Microhelp
usage(){
cat <<EOF
------------------------------------------
Acquisisce i files della banca e li importa sullo schema LIQUIDITA

Utilizzo : $0 [-h] [db]
 -h : questa schermata
 -d : acquisisce i dati della cartella e li sposta

 file: Nome del file da acquisire 
------------------------------------------
$1
EOF
}

# Funzione di acquisizione
acquisisci(){

filename=$(echo $1)
filename_only=$(basename $1)
md5=e$(md5sum ${filename} | awk '{ print $1 }')

export ctltmpfile=$(mktemp)


# Control file
echo "

LOAD DATA
INFILE '$filename' 
BADFILE 'hr.bad'
DISCARDFILE 'hr.dsc'

INTO TABLE T1_HR
TRUNCATE
WHEN (TIPO_RECORD='HR')
(
MD5 CONSTANT '${md5}',
NOME_FILE CONSTANT '${filename_only}',
TIPO_RECORD POSITION (1:2),
DATA_ORA_FLUSSO POSITION (3:21),
TIPO_FLUSSO POSITION (22:22),
CODICE_ABI_BT POSITION (23:27),
CODICE_ENTE_BT POSITION (28:34),
TIPO_SERVIZIO POSITION (35:42),
AID POSITION (43:48),
NUMERO_RICEVUTE POSITION (49:55)
)

INTO TABLE T1_RR
TRUNCATE
WHEN (TIPO_RECORD='RR')
(
MD5 CONSTANT '${md5}',
NOME_FILE CONSTANT '${filename_only}',
TIPO_RECORD POSITION (1:2), 
PROGRESSIVO_RICEVUTA POSITION (3:9), 
ID_TIPO POSITION (10:11), 
ID_DATA_MESSAGGIO POSITION (12:19), 
ID_ORA_MESSAGGIO POSITION (20:23), 
FIRMA_NOME POSITION (24:93), 
FIRMA_DATA POSITION (94:101), 
FIRMA_ORA POSITION (102:105), 
ESITO_DERIVATO POSITION (106:107), 
DATA_ORA_CREA_RICEVUTA POSITION (108:126), 
QUALIFICATORE POSITION (127:129), 
CODICE_ABI_BT POSITION (130:134), 
CODICE_ENTE POSITION (135:145), 
DESCRIZIONE_ENTE POSITION (146:175), 
CODICE_ENTE_BT POSITION (176:182), 
DATA_ORA_RICEVUTA POSITION (183:201), 
NUMERO_DOCUMENTO POSITION (202:208), 
CODICE_FUNZIONE POSITION (209:210), 
NUMERO_ORDINATIVO POSITION (211:217), 
PROGRESSIVO_ORDINATIVO POSITION (218:224), 
DATA_ORDINATIVO POSITION (225:234), 
ESERCIZIO POSITION (235:238), 
CODICE_ESITO POSITION (239:240), 
DESCRIZIONE_ESITO POSITION (241:310), 
DATA_PAGAMENTO POSITION (311:320), 
IMPORTO_ORDINATIVO POSITION (321:335), 
CODICE_PAGAMENTO POSITION (336:337), 
IMPORTO_RITENUTE POSITION (338:352), 
FLAG_COPERTURA POSITION (353:353), 
VALUTA_BENEFICIARIO POSITION (354:363), 
VALUTA_ENTE POSITION (364:373), 
ABI_BENEFICIARIO POSITION (374:378), 
CAB_BENEFICIARIO POSITION (379:383), 
NUM_CC_BENEFICIARIO POSITION (384:395), 
IBAN POSITION (396:429), 
CARICO_BOLLO POSITION (430:430), 
IMPORTO_BOLLO POSITION (431:437), 
CARICO_COMMISSIONI POSITION (438:438), 
IMPORTO_COMMISSIONI POSITION (439:445), 
CARICO_SPESE POSITION (446:446), 
IMPORTO_SPESE POSITION (447:453), 
NUMERO_ASSEGNO POSITION (454:473), 
DATA_EMISSIONE_ASSEGNO POSITION (474:483), 
DATA_ESTINZIONE_ASSEGNO POSITION (484:493), 
CODICE_VERSAMENTO POSITION (494:498), 
NUMERO_PRATICA POSITION (499:514), 
CAUSALE_PRATICA POSITION (515:559), 
NUM_PROPORTA_REVERSALE POSITION (560:566), 
NOME_COGNOME POSITION (567:706), 
INDIRIZZO POSITION (707:736), 
CAP POSITION (737:741), 
LOCALITA POSITION (742:771), 
PROVINCIA POSITION (772:773), 
PARTITA_IVA POSITION (774:784), 
CODICE_FISCALE POSITION (785:800), 
CAUSALE POSITION (801:1170), 
NUM_PAG_FUNZ_DEL POSITION (1171:1177), 
PRG_PAG_FUNZ_DEL POSITION (1178:1184), 
COD_ENTE_BENEFICIARIO POSITION (1185:1191), 
DESCRIZIONE POSITION (1192:1221), 
NUM_CRO POSITION (1222:1232), 
NUM_CONTO_TES POSITION (1233:1239)
)

INTO TABLE T1_DR
TRUNCATE
WHEN (TIPO_RECORD='DR')
(
MD5 CONSTANT '${md5}',
NOME_FILE CONSTANT '${filename_only}',
TIPO_RECORD POSITION (1:2),
PROGRESSIVO_RICEVUTA POSITION (3:9),
NUMERO_RICEVUTA POSITION (10:16),
IMPORTO_RICEVUTA POSITION (17:31)
)

INTO TABLE T1_ER
TRUNCATE
WHEN (TIPO_RECORD='ER')
(
MD5 CONSTANT '${md5}',
NOME_FILE CONSTANT '${filename_only}',
TIPO_RECORD POSITION (1:2), 
DATA_ORA_FLUSSO POSITION (3:21), 
TIPO_FLUSSO POSITION (22:22), 
CODICE_ABI_BT POSITION (23:27), 
CODICE_ENTE_BT POSITION (28:34), 
TIPO_SERVIZIO POSITION (35:42), 
AID POSITION (43:48), 
NUM_RICEVUTE POSITION (49:55)
)
" > $ctltmpfile


sqlldr userid=/@app_liquidita_${ambiente} SILENT=\(HEADER\) ROWS=10000 control=$ctltmpfile

sqlplus -S -L /@app_liquidita_${ambiente}  << EOF
exec ACQUISISCI_MIF ('${md5}')
EOF


}

# Elabora la cartella
# -------------------
elabora_dir(){

export HOMEDIR=/mnt/shared/FTP/Produzione/MIF

export DESTINATION_PATH=$HOMEDIR/ELABORATI/

export SOURCE_FILES_LIST=$(ls $HOMEDIR/DA_ELABORARE/* 2>/dev/null)


if [ "x${SOURCE_FILES_LIST}" = "x" ]; then
  echo "INFO: Nessun file trovato"
else

for file_corrente in ${SOURCE_FILES_LIST}; do
  echo ">>> Elaboro ${file_corrente}"
  echo "---------------------------------------"
  acquisisci $file_corrente
  mv ${file_corrente} ${DESTINATION_PATH}
done

fi

}

# MAIN
# ====
if [ "$1" = "-h" ]; then usage ""; exit 0; fi
if [ "$1" = "-d" ]; then elabora_dir ""; exit 0; fi
if [ "$1" = "-f" ]; then acquisisci $2; exit 0; fi
if [ "$1" = "" ];   then usage ""; exit 0; fi
if [ ! -f "$1" ];   then usage "File not exist!" ; exit 1; fi








